package pl.edu.pja.strategy;

public enum SimulationStrategy {

    NO_GENDER_QUOTA,
    NO_WOMEN_MANAGERS,
    FIFTY_PERCENT_WOMEN_MANAGERS,
    SEVENTY_FIVE_PERCENT_WOMEN_MANAGERS,
    ONE_HUNDRED_PERCENT_WOMEN_MANAGERS

}
